local repo 			    = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/" 
local Library 		  = loadstring(game:HttpGet(repo .. "Library.lua"))() 
local ThemeManager  = loadstring(game:HttpGet(repo .. "addons/ThemeManager.lua"))() 
local SaveManager   = loadstring(game:HttpGet(repo .. "addons/SaveManager.lua"))()
local Options 		  = Library.Options
local Toggles 		  = Library.Toggles
local Ver 			    = loadstring(game:HttpGet("https://raw.githubusercontent.com/limeroblox/meowware.lua/refs/heads/main/core/version.txt"))()
local Version 		  = "MeowWare.lua | " .. Ver
Library.ForceCheckbox = false 
Library.ShowToggleFrameInKeybinds = true 
